## Data Science Outlook
## Authors:
    Kathleen Freeberg
    Smita Sharma
    Sanheev Mankar
    
 ## Jobs Data Cleanup

In [12]:
%matplotlib inline
import pandas as pd
import numpy as np
import os
import matplotlib
import folium
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
#Open monster csv file 
csv_path=os.path.join("..","Sources", "monster_com-job_sample.csv")

jobs_data = pd.read_csv(csv_path)
jobs_data.columns

jobs_data_df=pd.DataFrame(jobs_data)

# Convert all data in job_title and job_description to lowercase 
jobs_data_df.loc[:,'job_title']=jobs_data['job_title'].str.lower()
jobs_data_df.loc[:,'job_description']=jobs_data['job_title'].str.lower()


#jobs_data_df.loc[jobs_data_df['organization'].isnull(),'Not Classified'] 
jobs_data_df.head(15)

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,it support technician job in madison,it support technician job in madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,business reporter/editor job in madison,business reporter/editor job in madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,johnson & johnson family of companies job appl...,johnson & johnson family of companies job appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,engineer - quality job in dixon,engineer - quality job in dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,shift supervisor - part-time job in camphill,shift supervisor - part-time job in camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c
5,United States of America,US,NaN,No,jobs.monster.com,construction pm - charlottesville job in charl...,construction pm - charlottesville job in charl...,Full Time Employee,"Charlottesville, VA",Computer/IT Services,http://jobview.monster.com/construction-pm-cha...,NaN,Experienced (Non-Manager),1e2637cb5f7a2c4615a99a26c0566c66
6,United States of America,US,NaN,No,jobs.monster.com,cybercoders job application for principal qa e...,cybercoders job application for principal qa e...,"Full Time, Employee",Contact name Tony Zerio,Computer Software,http://jobview.monster.com/principal-qa-engine...,NaN,NaN,455802d725fde67293970ab3953b1d39
7,United States of America,US,NaN,No,jobs.monster.com,mailroom clerk job in austin,mailroom clerk job in austin,Full Time Employee,"Austin, TX 73301",NaN,http://jobview.monster.com/mailroom-clerk-job-...,NaN,Experienced (Non-Manager),549a0541e4452ecd155efc032aaa72d7
8,United States of America,US,NaN,No,jobs.monster.com,housekeeper job in austin,housekeeper job in austin,Part Time Employee,"Austin, TX 78746",Hotels and Lodging Personal and Household Serv...,http://jobview.monster.com/housekeeper-job-aus...,NaN,Customer Support/Client Care,a6a2b5e825b8ce1c3b517adb2497c5ed
9,United States of America,US,NaN,No,jobs.monster.com,video data management /transportation technici...,video data management /transportation technici...,NaN,"Chesterfield, MO",NaN,http://jobview.monster.com/video-data-manageme...,NaN,NaN,73a9ba2b706e02628fa22ca1357174b1
10,United States of America,US,NaN,No,jobs.monster.com,aflac insurance sales agent job in berryville,aflac insurance sales agent job in berryville,Full Time,"Berryville, VA 22611",Insurance,http://jobview.monster.com/aflac-insurance-sal...,NaN,Customer Support/Client Care,2f8bdf60db4d85627ab8f040e67aa78d
11,United States of America,US,NaN,No,jobs.monster.com,sales associate job in columbus,sales associate job in columbus,Full Time Employee,"Columbus, IN",Business Services - Other,http://jobview.monster.com/Sales-Associate-Job...,NaN,Customer Support/Client Care,3a2adeacbf35985a508f630661eebb43
12,United States of America,US,NaN,No,jobs.monster.com,junior proofreader job in boston,junior proofreader job in boston,Full Time,"Boston, MA",NaN,http://jobview.monster.com/Junior-Proofreader-...,NaN,NaN,dd244d1299cf62058c71cef022bcfab3
13,United States of America,US,NaN,No,jobs.monster.com,primrose private preschool teacher job in houston,primrose private preschool teacher job in houston,Full Time,"Houston, TX 77098",Education,http://jobview.monster.com/Primrose-Private-Pr...,9.00 - 13.00 $ /hour,Entry Level,b43c077756d5a326c4854e1399fd2464
14,United States of America,US,NaN,No,jobs.monster.com,superintendent job in houston,superintendent job in houston,Full Time Employee,"Houston, TX",Construction - Industrial Facilities and Infra...,http://jobview.monster.com/Superintendent-Job-...,"80,000.00 - 95,000.00 $ /year",Building Construction/Skilled Trades,d8491fcefe14d1398de419984dccf427

In [14]:
#Search for a job location (state) within the location column and save it to a new column and save to the dataframe jobs_data_df

state_search= ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL',
                  'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 
                  'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 
                  'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')

pat = '|'.join(r"\b{}\b".format(x) for x in state_search)
jobs_data_df['state'] = jobs_data_df['location'].str.extract('('+ pat + ')', expand=False)
jobs_data_df = jobs_data_df[jobs_data_df['state'].notna()]

csv_path=os.path.join("..","Cleaned Data", "jobs.csv")
jobs_data_df.to_csv(csv_path)

In [15]:
#Search for Data Science jobs
csv_path=os.path.join("..", "Cleaned Data", "jobs.csv")
ds_jobs_data_df = pd.read_csv(csv_path)


job_title_search=("data sci", "machine learn", "data analy", "data min", "statist",
                 "big data", "business intelligence", "analytic","data engineer", "business analy",
                  "database admin", "data specia")

pat = '|'.join (job_title_search)

ds_jobs_data_df=jobs_data_df.loc[jobs_data_df['job_title'].str.contains(pat), :]

ds_jobs_data_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id,state
244,United States of America,US,NaN,No,jobs.monster.com,business analyst job in santa cruz,business analyst job in santa cruz,NaN,"Santa Cruz, CA",NaN,http://jobview.monster.com/Business-Analyst-Jo...,NaN,Engineering,5bfd3b75a363ed7f56ca0535686c2603,CA
324,United States of America,US,NaN,No,jobs.monster.com,business analyst job in las vegas,business analyst job in las vegas,Full Time Employee,"Las Vegas, NV",Computer/IT Services,http://jobview.monster.com/business-analyst-jo...,NaN,Experienced (Non-Manager),0cfe8e1701c1cf62f02c27ea0e259616,NV
331,United States of America,US,NaN,No,jobs.monster.com,business analyst associate job in san francisco,business analyst associate job in san francisco,Full Time Temporary/Contract/Project,"San Francisco, CA 94108",All,http://jobview.monster.com/business-analyst-as...,NaN,Business/Strategic Management,3ea54cca80f6790bb99f6a3f82995585,CA
345,United States of America,US,NaN,No,jobs.monster.com,sr. business analyst job in omaha,sr. business analyst job in omaha,Full Time Employee,"Omaha, NE 68124",Business Services - Other,http://jobview.monster.com/sr-business-analyst...,NaN,Business/Strategic Management,85d369c3fc64c11b3856d8a636659ba4,NE
385,United States of America,US,NaN,No,jobs.monster.com,business analyst i job in oak brook,business analyst i job in oak brook,"Full Time, Temporary/Contract/Project","Oak Brook, IL 60521",NaN,http://jobview.monster.com/business-analyst-i-...,NaN,Experienced (Non-Manager),21e316b856c704ea93decf447dc2c007,IL

In [16]:
#Clean up the Industry categories

ds_jobs_data_df.loc[ds_jobs_data_df['organization'].isnull(), 'organization']= ds_jobs_data_df['sector'] 
ds_jobs_data_df.loc[ds_jobs_data_df['organization']=='All', 'organization']= ds_jobs_data_df['sector'] 

ds_jobs_data_df.head()

/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id,state
244,United States of America,US,NaN,No,jobs.monster.com,business analyst job in santa cruz,business analyst job in santa cruz,NaN,"Santa Cruz, CA",Engineering,http://jobview.monster.com/Business-Analyst-Jo...,NaN,Engineering,5bfd3b75a363ed7f56ca0535686c2603,CA
324,United States of America,US,NaN,No,jobs.monster.com,business analyst job in las vegas,business analyst job in las vegas,Full Time Employee,"Las Vegas, NV",Computer/IT Services,http://jobview.monster.com/business-analyst-jo...,NaN,Experienced (Non-Manager),0cfe8e1701c1cf62f02c27ea0e259616,NV
331,United States of America,US,NaN,No,jobs.monster.com,business analyst associate job in san francisco,business analyst associate job in san francisco,Full Time Temporary/Contract/Project,"San Francisco, CA 94108",Business/Strategic Management,http://jobview.monster.com/business-analyst-as...,NaN,Business/Strategic Management,3ea54cca80f6790bb99f6a3f82995585,CA
345,United States of America,US,NaN,No,jobs.monster.com,sr. business analyst job in omaha,sr. business analyst job in omaha,Full Time Employee,"Omaha, NE 68124",Business Services - Other,http://jobview.monster.com/sr-business-analyst...,NaN,Business/Strategic Management,85d369c3fc64c11b3856d8a636659ba4,NE
385,United States of America,US,NaN,No,jobs.monster.com,business analyst i job in oak brook,business analyst i job in oak brook,"Full Time, Temporary/Contract/Project","Oak Brook, IL 60521",Experienced (Non-Manager),http://jobview.monster.com/business-analyst-i-...,NaN,Experienced (Non-Manager),21e316b856c704ea93decf447dc2c007,IL

In [17]:
#Reclassify Industries

ds_jobs_data_df.loc[ds_jobs_data_df.organization == 'Biotech/R&D/Science', 'organization']='Biotechnology/Pharmaceuticals' 
ds_jobs_data_df.loc[ds_jobs_data_df.organization =='Computer/IT Services','organization']='Technology' 
ds_jobs_data_df.loc[ds_jobs_data_df.organization =='IT/Software Development','organization']='Technology' 
ds_jobs_data_df.loc[ds_jobs_data_df.organization =='Computer Hardware','organization']='Technology' 
ds_jobs_data_df.loc[ds_jobs_data_df.organization =='Experienced (Non-Manager)','organization']='Other/Not Classified' 

csv_path=os.path.join("..","Cleaned Data", "ds_jobs.csv")
ds_jobs_data_df.to_csv(csv_path)

/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys